package hw3;

public class TerrainFileException extends Exception {
	private static final long serialVersionUID = 2099351686322997836L; // generated by java after error

	public TerrainFileException(String message) {
        super(message);
    }
}
